maps/de_sampa.txt
gfx/env/sampalf.tga
gfx/env/sampadn.tga
gfx/env/sampaft.tga
gfx/env/sampabk.tga
gfx/env/sampart.tga
gfx/env/sampaup.tga
models/sampa/busgib.mdl
models/sampa/cervagib.mdl
models/sampa/fumaca.spr
models/sampa/garrafa.mdl
models/sampa/josias.mdl
models/sampa/pneu.mdl
sound/sampa/cachorro.wav
sound/sampa/djzp.wav
sound/sampa/flipper.wav
sound/sampa/garoa.wav
sound/sampa/josias1.wav
sound/sampa/josias2.wav
sound/sampa/josias3.wav
sound/sampa/josias4.wav
sound/sampa/josias5.wav
sound/sampa/josias6.wav
sound/sampa/metro_vent.wav
sound/sampa/misterio.wav
sound/sampa/neon.wav
sound/sampa/panico.wav
sound/sampa/ruas.wav
sound/sampa/saleta.wav
sound/sampa/sso.wav
overviews/de_sampa.bmp
overviews/de_sampa.txt
